### ISSUE TITLE
Wrong format string for long long

### ISSUE THREAD

**Issue by jonathangjertsen** [htibosch/freertos_plus_projects#3]
The current implementation uses `%Lu`/`%Ld` for long long, but according to https://cplusplus.com/reference/cstdio/printf/ it should be `%llu`/`%lld` . Is this intentional?

Fix:

```patch
 		if( ch == 'l' )
 		{
 			ch = *( format++ );
-			apBuf->flags.long32 = 1;
-			/* Makes not difference as u32 == long */
-		}
-		if( ch == 'L' )
-		{
-			ch = *( format++ );
-			apBuf->flags.long64 = 1;
-			/* Does make a difference */
+			if (ch == 'l')
+			{
+				apBuf->flags.long64 = 1;
+				ch = *( format++ );
+			}
+			else
+			{
+				apBuf->flags.long32 = 1;
+			}
 		}
```

**Comment by htibosch** [comment]
Thank you for notifying me about this.

Throughout the years I found both "`%Lu`" as well as "`%llu`".

What about allowing for both formats?

~~~c
        if( ch == 'l' )
        {
            ch = *( format++ );
            if( ch != 'l')
            {
                /* A format like "lu". */
                apBuf->flags.long32 = 1;
            }
            else
            {
                /* A format like "llu". */
                ch = *( format++ );
                apBuf->flags.long64 = 1;
            }
        }

        if( ch == 'L' )
        {
            /* A format like "llu". */
            ch = *( format++ );
            apBuf->flags.long64 = 1;
        }
~~~

**Comment by jonathangjertsen** [comment]
Sure, that's probably for the best to avoid breaking any code that uses %L.

**Comment by htibosch** [comment]
Jonathan, not sure if you saw it but I updated [printf-stdarg.c](https://github.com/htibosch/freertos_plus_projects/blob/master/plus/Framework/Utilities/printf-stdarg.c#L763)

Wish you a good year!

Hein

**Comment by htibosch** [comment]
Hello Jonathan,

The feature [request #691](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/691) was closed before I had responded.

[Here](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/691#issuecomment-1417082267) is my response.

Thanks

**Comment by jonathangjertsen** [comment]
> Jonathan, not sure if you saw it but I updated [printf-stdarg.c](https://github.com/htibosch/freertos_plus_projects/blob/master/plus/Framework/Utilities/printf-stdarg.c#L763)
> 
> Wish you a good year!
> 
> Hein

Thanks! I guess this can be closed then
